### ISSUE TITLE
Feature request: firmware file upload form.

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/revk#1]
This has already come up several times. Currently RevK only supports "pull" form of updates, i. e. it goes to some server and checks for new versions. It turns out for experiments, quick tests, etc, that's not the optimal way, because it requires rolling your own server for test purposes. What if we have binary upload form as an option, like in ESPHome ?

**Comment by revk** [comment]
It uses signed binaries.

If you build your own, you can make it pull from your server no problem.

Same way I do tests.

**Comment by Sonic-Amiga** [comment]
I see. I cannot switch from custom build to upstream and back because signatures differ. Just tried, it downloads the F/W, but ends up in "upgrade failed"

**Comment by Sonic-Amiga** [comment]
Okay, i see, appears not so useful. Closing.

**Comment by revk** [comment]
You can if you USB flash a custom bootloader first.
