### ISSUE TITLE
Feature request: explain, why upgrade failed.

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/revk#2]
There can be different possibilities. Host not found, cannot connect, file not found, signature mismatch, etc. Would be nice if together with "upgrade failed" the user actually sees some explanation. It may seriously aid diagnostics.

Perhaps esp_err_t needs to be decoded into a human-readable text and displayed.

**Comment by revk** [comment]
The error code is logged to MQTT. I cannot find `upgrade failed` in the code!

We do a restart with `OTA Download fail`

I'll make it log differently for validate failed...
