### ISSUE TITLE
8mb vs 4mb csv

### ISSUE THREAD

**Issue by Sonic-Amiga** [revk/revk#3]
Hello! Just noticed that these CSVs are 1:1 identical; and addresses actually suggest 4MB flash. Is this intentional or i'm missing something ?

**Comment by revk** [comment]
Plan was to make second 4M a filing system perhaps. There is code to update partition table in situ if needed so it could be updated when we have a use for it.

**Comment by Sonic-Amiga** [comment]
So you confirm that the image is in fact 4MB and it's correct as intended ? Okay, thank you.
